version: '3.8'
services:
  frontend:
    image: luvisjostonj/pyapp-frontend:test
    container_name: front-end
    ports:
      - "80:5000"
    networks:
      - app-network

  backend:
    image: luvisjostonj/pyapp-backend:test
    container_name: back-end
    ports:
      - "5001:5001"
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

