version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:5000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
