name: Docker Image CIl

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . --file frontend/Dockerfile --tag luvisjostonj/pyapp-frontend:test
        docker build . --file backend/Dockerfile --tag luvisjostonj/pyapp-backend:test
        docker push luvisjostonj/pyapp-frontend:test
        docker push luvisjostonj/pyapp-backend:test
    - name: Log out from Docker Hub
      run: docker logout
