name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . --file frontend/Dockerfile --tag luvisjostonj/pyapp-frontend:test
        docker build . --file backend/Dockerfile --tag luvisjostonj/pyapp-backend:test
        docker push luvisjostonj/pyapp-frontend:test
        docker push luvisjostonj/pyapp-backend:test
    - name: Log out from Docker Hub
      run: docker logout

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -i "pem.pem" -o StrictHostKeyChecking=no ubuntu@ec2-54-158-172-115.compute-1.amazonaws.com<< 'EOF'
        scp -i "pem.pem" -o StrictHostKeyChecking=no pyhton-backend-repo/docker-compose.yml ubuntu@54.158.172.115:/home/ubuntu
        sudo docker-compose -f ~/docker-compose.yml up -d 
        EOF
